"use client";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {gsap} from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
const base="/pirpir";
export default function PirpirStory({lang="en"}:{lang?:"en"|"tr"}){
 const [cardsOpen,setCardsOpen]=useState(false);
 const root=useRef<HTMLElement>(null),box=useRef<HTMLImageElement>(null);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const frames=Array.from({length:48},(_,i)=>{const img=new Image();img.src=`${base}/box/frames/box-${String(i).padStart(3,'0')}.webp`;return img});const state={frame:0};const ctx=gsap.context(()=>{const tl=gsap.timeline({scrollTrigger:{trigger:root.current,start:'top 80%',end:'bottom 25%',scrub:.5}});tl.to(state,{frame:47,duration:1,ease:'none',onUpdate:()=>{if(box.current)box.current.src=frames[Math.round(state.frame)].src}},0).fromTo('.pack-item',{x:0,y:65,scale:.65,opacity:0},{x:0,y:0,scale:1,opacity:1,stagger:.06,duration:.7,ease:'power2.out'},.2);},root);return()=>ctx.revert()});return()=>mm.revert()},[]);
 const item=(cls:string,src:string,name:string)=><button className={`pack-item ${cls}`} aria-label={name}><img src={`${base}/${src}`} alt={name}/></button>;
 return <section className="pirpir-pack-banner" ref={root} aria-label={lang==="en"?"Pırpır companion design set":"Pırpır tasarım seti"}><div className="pirpir-pack-stage"><img className="pack-box" ref={box} src={`${base}/box/frames/box-047.webp`} alt={lang==="en"?"Pırpır box that opens while scrolling":"Scroll ile açılan Pırpır kutusu"}/>{item('pack-bag','bag-cutout.webp',lang==="en"?'Tote bag':'Bez çanta')}{item('pack-calendar','calendar/duygu-takvimi.webp',lang==="en"?'Emotion calendar':'Duygu takvimi')}<button className={`pack-item pack-card-fan ${cardsOpen?'is-open':''}`} aria-label={lang==="en"?"Open or close the question cards":"Soru kartlarını aç veya kapat"} aria-expanded={cardsOpen} onClick={()=>setCardsOpen(!cardsOpen)}><span className="fan-cards">{Array.from({length:10},(_,i)=><img key={i} style={{'--fan-x':`${(i-4.5)*19}px`,'--fan-angle':`${(i-4.5)*7}deg`,'--fan-y':`${Math.abs(i-4.5)*5}px`} as CSSProperties} src={`${base}/cards/soru-${String(i+1).padStart(2,'0')}.webp`} alt={`${lang==="en"?'Question card':'Soru kartı'} ${i+1}`}/>)}</span><img className="fan-cover" src={`${base}/cards/arka-yuz.webp`} alt={lang==="en"?"Question card back":"Soru kartları ortak yüzü"}/></button><div className="pack-item pack-sticker-group" aria-label={lang==="en"?"Emotion stickers":"Duygu stickerları"}>{[['mutlu','Mutlu'],['sakin','Sakin'],['ofkeli','Öfkeli'],['kaygili','Kaygılı'],['saskin','Şaşkın'],['kafasi-karismis','Kafası karışmış']].map(([id,name])=><button key={id} aria-label={name}><img src={`${base}/stickers/${id}.webp`} alt={name}/></button>)}</div></div></section>
}
