"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowUpRight,ChevronDown,RotateCcw,X} from "lucide-react";
export default function ProjectExperience({kind,title,description,type,url,demo=false,lang="en"}:{kind:"game"|"website";title:string;description?:string;type?:string;url:string;demo?:boolean;lang?:"en"|"tr"}){
 const [revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[nearby,setNearby]=useState(false),[expanded,setExpanded]=useState(false),[isMobile,setIsMobile]=useState(false);
 const viewport=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(640);
 useEffect(()=>{const query=window.matchMedia("(max-width: 800px)");const update=()=>setIsMobile(query.matches);update();query.addEventListener("change",update);return()=>query.removeEventListener("change",update)},[]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));observer.observe(el);return()=>observer.disconnect()},[]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setNearby(true);observer.disconnect()}},{rootMargin:"500px"});observer.observe(el);return()=>observer.disconnect()},[]);
 const screen=<>{nearby&&<iframe loading="lazy" key={revision} src={url} title={title} onLoad={()=>setLoaded(true)} allow="fullscreen 'none'" sandbox={demo?"allow-scripts allow-popups":"allow-scripts allow-same-origin allow-forms allow-pointer-lock"} style={kind==="website"?(isMobile?{width:"100%",height:"100%",transform:"none"}:{width:1280,height:800,transform:`scale(${width/1280})`,transformOrigin:"top left"}):undefined}/>} {!loaded&&<span className="experience-loading" role="status">{lang==="en"?"Loading…":"Yükleniyor…"}</span>}</>;
 return <div className={`compact-experience compact-${kind} ${expanded?"mobile-site-open":""} ${isMobile?"is-mobile-preview":""}`}>
 {kind==="website"&&<button type="button" className="mobile-website-row" aria-expanded={expanded} onClick={()=>setExpanded(true)}><span><strong>{title}</strong><small>{type}</small></span><ChevronDown size={20}/></button>}
 {kind==="game"?<div className="game-book-composition"><img className="game-source-book" src="/pirpir/book.webp" alt="Oyuna ilham veren Pırpır Sakinleşiyor — Çağrı Odabaşı" loading="lazy" decoding="async"/><div className="compact-phone"><div className="compact-phone-camera" aria-hidden="true"/><div className="compact-phone-screen" ref={viewport}>{screen}</div></div></div>:<div className="website-mobile-panel"><button type="button" className="mobile-site-close" onClick={()=>setExpanded(false)} aria-label={lang==="en"?"Close website preview":"Site önizlemesini kapat"}><X size={20}/></button><p className="mobile-site-description">{description}</p><div className="compact-browser"><div className="compact-browser-bar"><span className="compact-browser-dots" aria-hidden="true">•••</span><span>{demo?`${title} · Demo`:new URL(url).hostname}</span><a href={url} target="_blank" rel="noreferrer" aria-label={lang==="en"?"Open website in a new tab":"Web sitesini ayrı sekmede aç"}><ArrowUpRight size={16}/></a></div><div className="compact-browser-screen" ref={viewport}>{screen}</div></div></div>}
 <div className={`compact-device-controls ${kind==="game"?"game-controls":""}`}><button type="button" onClick={()=>{setLoaded(false);setRevision(v=>v+1)}}><RotateCcw size={14}/>{lang==="en"?"Restart":"Yeniden başlat"}</button></div>
 </div>;
}
